import jsPDF from "jspdf";

export const convertMonthDataToPdf = (summarizedMonthData) => {
    // Create a new jsPDF instance
    const doc = new jsPDF();
  
    // Set the title for your PDF
    const pageWidth = doc.internal.pageSize.getWidth();
    const textWidth = doc.getStringUnitWidth('INVOICE') * doc.internal.getFontSize();
    const xCenter = (pageWidth - textWidth) / 2;

// Set the title for your PDF
    doc.setFontSize(16);
    doc.text('INVOICE', xCenter, 10);
  
    // Add a date (replace 'Random Date' with the actual date)
    doc.setFontSize(12);
    doc.text(`Date: Random Date`, 10, 20);
  
    // Add a section for 'Summary Report'
    doc.setFontSize(14);
    doc.text('Summary Report', 10, 30);
  
    // Add 'From' and 'To' details (replace with actual names)
    doc.setFontSize(12);
    doc.text('From: Autogenerated', 10, 40);
    doc.text('To: Joyce', 10, 50);
  
    // Loop through your summarized month data and add it to the PDF
    let y = 70; // Initial vertical position
  
    summarizedMonthData.forEach((month) => {
      doc.setFontSize(12);
      doc.text(`Month: ${month.month}`, 10, y);
  
      // Create rectangles for the grid
      doc.rect(10, y + 10, 60, 10); // Rectangle for 'Total Packets'
      doc.rect(70, y + 10, 60, 10); // Rectangle for the value
  
      doc.rect(10, y + 20, 60, 10); // Rectangle for 'Total Plates'
      doc.rect(70, y + 20, 60, 10); // Rectangle for the value
  
      // Add labels and values inside the rectangles
      doc.text('Total Packets', 15, y + 15);
      doc.text(`${month.totalPackets}`, 75, y + 15);
  
      doc.text('Total Plates', 15, y + 25);
      doc.text(`${month.totalPlates}`, 75, y + 25);
  
      y += 40; // Increase vertical position for the next month
    });
  
    // Save or download the PDF
    doc.save('summary_report.pdf');
  };
  